services:
  server:
    container_name: model_gen
    build:
      context: .
    working_dir: /src/app
    ports:
      - 8000:8000
    restart: always
    volumes:
      - .:/src
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_MULTIPLE_DATABASES=app,app_test
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
 db-data:
secrets:
  db-password:
    file: db/password.txt
